<?php
return [
    'mpesa' => [
        'form_params' => [
            'c2b' => [
                'ShortCode',
                'CommandID',
                'Amount',
                'Msisdn',
                'BillRefNumber',
            ],
            'b2c' => [
                'InitiatorName',
                'SecurityCredential',
                'CommandID',
                'Amount',
                'PartyA',
                'PartyB',
                'Remarks',
                'QueueTimeOutURL',
                'ResultURL',
                'Occasion',
            ],
            'b2b' => [
                'Initiator',
                'SecurityCredential',
                'CommandID',
                'SenderIdentifierType',
                'ReceiverIdentifierType',
                'Amount',
                'PartyA',
                'PartyB',
                'AccountReference',
                'Remarks',
                'QueueTimeOutURL',
                'ResultURL',
            ],
            'reversal' => [
                'CommandID',
                'Initiator',
                'SecurityCredential',
                'TransactionID',
                'Amount',
                'ReceiverParty',
                'ReceiverIdentifierType',
                'ResultURL',
                'QueueTimeOutURL',
                'Remarks',
                'Occasion',
            ],
            'account_balance' => [
                'CommandID',
                'Initiator',
                'SecurityCredential',
                'PartyA',
                'IdentifierType',
                'Remarks',
                'QueueTimeOutURL',
                'ResultURL',
            ],
            'transaction_status' => [
                'Initiator',
                'SecurityCredential',
                'CommandID',
                'TransactionID',
                'PartyA',
                'IdentifierType',
                'ResultURL',
                'QueueTimeOutURL',
                'Remarks',
                'Occasion',
            ],
            'stk_push' => [
                'BusinessShortCode',
                'Password',
                'Timestamp',
                'TransactionType',
                'Amount',
                'PartyA',
                'PartyB',
                'PhoneNumber',
                'CallBackURL',
                'AccountReference',
                'TransactionDesc',
            ],
            'stk_push_query' => [
                'BusinessShortCode',
                'Password',
                'Timestamp',
                'CheckoutRequestID',
            ],
        ]
    ]
];
